import { Container } from "@chakra-ui/react";


const App = () => {

  return(
   <Container maxW='xl' margin='auto'>
    <h1>frjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov rjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov rjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov rjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov rjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov rjwfkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkfjdsfjjsafkjewjlfdjewbdmfewdewmirodilmavlonov 
    </h1>
   </Container>
  )
}

export default App;
